name: Documentation Generation
on: [workflow_dispatch,push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Automatically Generate Documentation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Generate Documentation via TypeDoc
        run: yarn run docs
      - name: Add CNAME
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ env.home}}/docs/CNAME
          contents: |
            statisfy.js.org
          write-mode: append
      - name: Commit Changes  
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Generated Documentation for Statisfy Site

