name: Documentation Generator
on: [workflow_dispatch,push]
jobs:
  build:
    name: DocGEN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: run docs # will run `yarn docs` command
